### ISSUE TITLE
Floppy drives not doing anything

### ISSUE THREAD

**Issue by qwert95** [Kingdread/floppymusic#1]
Tried using both 0-1 and 11-12 pins in drives.cfg because I didn't know if it was correct to use the WiringPi lib enumeration or the physical Raspberry GPIO pins one, but not working both ways.
Connected 3 different drives, still nothing.

I'm sure my configuration with wires etc. is ok because I can run this program and hear the song.
https://xtraperianer.wordpress.com/2014/08/06/making-floppy-music-with-a-raspberry-pi/

Trying to run this mid file
http://www.midiworld.com/midis/other/beethoven/beets3m3.mid

**Comment by Kingdread** [comment]
Since you've already verified that the drives work with other programs, I'm limiting myself to floppymusic.
- Could you try and set a dropfactor (`-d` on the commandline)? Maybe the original frequency is too high for your specific drive model, so that might help.
- Could you try and increase the delay in [`DriveManager.cpp line 43](https://github.com/Kingdread/floppymusic/blob/master/src/DriveManager.cpp#L43)? The comment explains what it does, increasing the loop count could fix your issue.

Also, what Pi model are you using? I've programmed this 2 years ago for model B, and since floppymusic does the GPIO directly, it may be possible that the memory mapping or something has actually changed.

**Comment by qwert95** [comment]
Hi, sorry for the delay and thank your for answering.
- I tried using the dropfactor parameter, no changes.
- I did some tests changing the loop count to 30,60,150,300,600,1000, still nothing achieved.

I'm working on the latest Pi 3, this could be the issue.
I should soon have chance to work on a Pi 2, I'll let you know.

**Comment by SebastianKluge** [comment]
The issue can be solved by reset the BCM2708_PERI_BASE to the 'new' Pi2/3 Address from 0x2000000 to 0x3F000000 (Take a look at line#4 in https://github.com/Kingdread/floppymusic/blob/master/src/gpio.hpp).

btw: Its a shame to reseed the gpio from rev a to b and numbering 'PINS' in Banana; WiringPi and more 'libs'.

also btw: The code by Kingdread is brill!

Regs
Sebastian

**Comment by qwert95** [comment]
Tested and working! Thank you guys very much!

**Comment by gioporta** [comment]
I have a Raspberry Pi 2 and I'm having the same issue, except changing the address and rebuilding from source is still not fixing the problem.

I'm using pins 11 and 12, and running the code from the RPi forum (https://www.raspberrypi.org/forums/viewtopic.php?f=41&t=69947) works fine, however this will not.

Any ideas?

EDIT:
I've now tried on my RPi 1 Model B (rev 1.1) and it still isn't working. The previously linked program still continues to work fine, but I cannot for the life of me figure out why this won't. I've set up my drives.cfg with _drive 11 12_, but it doesn't do anything. I get the following for output:

```
pi@piserver:~/floppymusic $ sudo ./floppymusic starwars.mid 
[floppymusic 6ce1af5a]
Reading drive configuration drives.cfg
Setting up GPIO
Setting up drives
Reading MIDI file
Merging 5 tracks
Ready, steady, go!
```

I've tried several different midi files to no avail, as well as changing the dropfactor, and compiling with _-DFASTIO_.

**Comment by Kingdread** [comment]
When you say pins 11 and 12, do you mean the pins with the physical numbers 11 and 12? Unfortunately, the pin numbering is a bit confusing, since each library using its own scheme. Take a look [here](https://pinout.xyz/), physical pins 11 and 12 should be 17 and 18. I think floppymusic needs the BCM number, though I'm not entirely sure anymore, just play around with it.

For the RPi 2, the patched version with 0x3F... as base address should otherwise work fine. There's a pull request #2 to include it, but it looks abandoned, so I will probably do it myself sometime.

**Comment by gioporta** [comment]
It was definitely the BCM number that fixed my issue, thank you! I recommend adding that to the readme for anyone else who has the same problem.

**Comment by Kingdread** [comment]
Good idea, will add a remainder to the readme!

**Comment by averagenokiauser** [comment]
> The issue can be solved by reset the BCM2708_PERI_BASE to the 'new' Pi2/3 Address from 0x2000000 to 0x3F000000 (Take a look at line#4 in https://github.com/Kingdread/floppymusic/blob/master/src/gpio.hpp).
> 
> btw: Its a shame to reseed the gpio from rev a to b and numbering 'PINS' in Banana; WiringPi and more 'libs'.
> 
> also btw: The code by Kingdread is brill!
> 
> Regs Sebastian

I am pretty sure that i need to do the same but for raspberry pi 4b. I just don't know the address of the pi4b sadly. I will try to find it somewhere but if someone here knows it, i would be happy if you send it.
