### ISSUE TITLE
After launch no sound

### ISSUE THREAD

**Issue by dalukac** [Kingdread/floppymusic#4]
Hi I have little problem with soft i have everything set up corectly..i tried that program [https://www.raspberrypi.org/forums/viewtopic.php?t=69947&p=994442](url) and my drive worked . I set the drives.cfg to `drives 17 18` and physically i have wires on 11 12 pins some advice what can i try ? i tried on diff pins but still nothing. I will be thankfull !

**Comment by creolis** [comment]
same here ... funny thing that two guys within 4 hrs are trying the same thing.
I have pretty much the same configuration, using GPIO17 and 18, but nothing happens after launching - the drive doesn't even twitch :-(

**Comment by creolis** [comment]
uhm ... @vetr0lam - did you by any chance directly connect your RPi to the floppy pinout? Or did you convert the RPi 3.3V control to 5V as needed by the drive?

**Comment by dalukac** [comment]
my wiring looks like floppy pin 18(dir) connected to pin11(bcm17) and floppy pin20(stepper) connected to pin12(bcm18) and pins 17,19 grounded on pin 6 on rpi and power from older atx. its here something else to be needed ?

**Comment by Kingdread** [comment]
Hm, are you running a newer model? If so, did you compile with `make MODEL=PI2`?

**Comment by creolis** [comment]
@vetr0lam well... the thing is - a usual floppy drive needs a voltage of 5V on its control pins for the stepper motor to actually do its thing. 

An arduino fires its GPIOs with 5V (this is why almost all tutorials just connect arduinos straight to the disk drive) while a RPi only uses 3.3V GPIO voltage. This means that if you just hook up your drive to the RPi without pulling the 3.3V up to 5V (e.g. by using an opto-isolator or even better a transistor), you might end up with a drive that's just "twitching" instead of moving.

**Comment by dalukac** [comment]
`make MODEL=PI2` solves my problem  it's runnig now, thanks !
